# Verilator
VERILATOR_PATH=$HOME/lib/verilator/bin
if [ -d $VERILATOR_PATH ]; then
	export PATH=$VERILATOR_PATH:$PATH
fi

# Verible
VERIBLE_PATH=$HOME/lib/verible/bin
if [ -d $VERIBLE_PATH ]; then
	export PATH=$VERIBLE_PATH:$PATH
fi

# SVUnit
SVUNIT_INSTALL=$HOME/lib/svunit
if [ -d $SVUNIT_INSTALL ]; then
	export SVUNIT_INSTALL
	export PATH=$PATH:$SVUNIT_INSTALL"/bin"
fi
