# SVUnit
SVUNIT_INSTALL=$HOME/lib/svunit
if [ -d $SVUNIT_INSTALL ]; then
	export SVUNIT_INSTALL
	export PATH=$SVUNIT_INSTALL"/bin":$PATH
fi

# SVUnit
SVUT=$HOME/lib/svut
if [ -d $SVUT ]; then
	export $SVUT
	export PATH=$SVUT:$PATH
fi

# Verible
VERIBLE_PATH=$HOME/lib/verible/bin
if [ -d $VERIBLE_PATH ]; then
	export PATH=$VERIBLE_PATH:$PATH
fi

# Verilator
VERILATOR_PATH=$HOME/lib/verilator/bin
if [ -d $VERILATOR_PATH ]; then
	export PATH=$VERILATOR_PATH:$PATH
fi